### PR TITLE
replace different way of declaring color and opacity

### PR DESCRIPTION
**Pull request by agrajaghh**
had some problems with some svg files where color and opacity was declared in a different way

### CODE REVIEW

**Comment by sebkur** [comment]
Thanks again, hopefully this works for more icons now!

**Comment by agrajaghh** [comment]
Unfortunately some programs like illustrator export files in black and without any transparency without any `fill` or `opacity` / `fill-opacity` atributes....

**Comment by sebkur** [comment]
Does this concern any icons from the Material Icons repository?

**Comment by agrajaghh** [comment]
I don't know, I think it were some files I created

**Comment by agrajaghh** [comment]
I just checked, seems like all the files in the material icons repo doesn't have any of our attributes :-1:

**Comment by agrajaghh** [comment]
Only possibility seems to do some xml parsing.... but thats probably overkill. Its not a big problem to open the svg's once in inkscape and change the color and opacity.

**Pull request merged**
