### PR TITLE
improve argument handling and add style-attribute replacement

### PR DESCRIPTION
**Pull request by agrajaghh**
Changes:
- use ArgumentParser to make argument handling easier
- make color, opacity and pngcrush optional
- remove fill and opacity properties from style Attribute if necessary
- remove the temp svg-file
- add .gitignore for .idea folder

If you like it, I'll adapt the readme and example files...

This might make the other script unnecessary, what do you think about removing it?

### CODE REVIEW

**Comment by sebkur** [comment]
Looks pretty good!

Yes, I think it's safe to remove the other script, the xml parser based version is much more robust.

Do you have example files where the manipulation of the style attribute comes into play?

**Comment by agrajaghh** [comment]
Yes, I can include them in the example folder. I'll update the PR later when I'm home...

**Comment by agrajaghh** [comment]
Did some more changes and included a svg-file I created with illustrator but changed color and opacity with inkscape. This lead to groups (`<g>`-Elements) with a style attribute: `style="fill:#008000;opacity:0.15"`. So its not enough to change color and opacity of the path element because the opacities will be multiplied. I'm removing opacities from groups now if the --opacity option is given.

The example is "broken" now for `ic_battery_50_48px` because the upper half of the battery already has an opacity of 0.5 which will be overwritten, but I guess this is intended behaviour if the opacity option is specified, no?

Are these changes okay for you?

**Comment by sebkur** [comment]
Sorry for the long absence. My original intention was to make the icons with some transparency like the battery work as well... I think for such files the multiplied opacity makes sense.

**Comment by agrajaghh** [comment]
hm, to make it work reliably for all files isn't easy. Currently the upper half of the battery has `fill-opacity=".3"` and we just add e.g. `opacity="0.54"` so they get multiplied (in master). But whats happening if there is already `opacity="0.3"`? We could read all values and multiply them ourselves but getting this done properly including groups is complicated I guess. What do you think?

**Comment by sebkur** [comment]
Indeed, a bit tricky. Maybe we could wrap an additional layer around the whole image and add the desired opacity there (so that the multiplying happens implicit without having to overwrite anything or carry out multiplications ourselves). This would keep the relative opacity between individual component of the input image.

In a way, it depends on what the user wants to happen with opacity already present in the image, should it be overwritten or effectively multiplied somehow... maybe we should add another CLI switch for that?

**Comment by agrajaghh** [comment]
Good idea with the wrapping! I'll try to do that. It helps too with cases where opacity="0" (don't know if thats possible) which would be displayed otherwise.

I'll think about the option to overwrite every opacity, but I'm not sure its really necessary...

**Comment by agrajaghh** [comment]
done, everything will be moved inside a `<g>` Element with an `opacitiy` attribute. I think thats the cleanest solution.

I'm not sure about offering the option to overwrite existing opacity-values... It adds more complexity and shouldn't happen often I guess.

**Pull request merged**
